<?php $this->getHeader($this->title, '', 1) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <?php $this->getTopSidebar() ?>
            <div id="members-content-wrap">
                <?php $this->getUsersNav() ?>
                <div class="clearfix">
                    <div id="members-content">
                        <div class="members-list-head clearfix">
                            <div class="ld"><h1>About</h1></div>
                            <div class="rd">
                                <ul class="member-head-tabs clearfix">
                                    <li class="active"><a href="<?= $this->lurl('girl/about') ?>">About Me<span class="mht-tip"></span></a></li>
                                    <li><a href="<?= $this->lurl('girl/lookbook') ?>">My Lookbook<span class="mht-tip"></span></a></li>
                                </ul>
                            </div>
                        </div> <!-- .members-list-head -->
                        <div class="clearfix content-after-subnav">
                            <div id="members-content-left">
                                <div id="members-content-left-top">
                                    <h2>
                                        samantha_1985
                                        <span class="member-age">31 Years</span>
                                    </h2>
                                    <div>
                                        Torrance, CA
                                        <span class="sep-bull">&bull;</span>
                                        Last Login: 3 hours ago
                                    </div>
                                </div> <!-- #members-content-left-top -->
                                <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fermentum ipsum.</h4>
                                <hr />
                                <div class="clearfix member-about">
                                    <div class="ld"><img src="<?= $this->baseUrl() ?>/images/clipart/about-woman.jpg" alt="" /></div>
                                    <div class="rd member-about-text">
                                        <h4>My Bio</h4>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim.</p>
                                    </div>
                                </div> <!-- .clearfix -->
                                <hr />
                                <h4>I&rsquo;m Looking For</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque</p>
                                <hr />
                                <h4>Our History</h4>
                                <div>
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1">damac713</div>
                                        <div class="mh-col-2">Viewed</div>
                                        <div class="mh-col-3">May 20</div>
                                    </div> <!-- .members-history-row clearfix -->
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1">Your activity</div>
                                        <div class="mh-col-2">You Kissed</div>
                                        <div class="mh-col-3">May 18</div>
                                    </div> <!-- .members-history-row clearfix -->
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1"></div>
                                        <div class="mh-col-2">You Kissed</div>
                                        <div class="mh-col-3">May 18</div>
                                    </div> <!-- .members-history-row clearfix -->
                                </div>

                            </div> <!-- #members-content-left -->
                            <div id="members-content-right">
                                <div class="members-blue">
                                    <h3>Personal Details</h3>
                                    <div class="clearfix">
                                        <div class="member-perks">
                                            <p>
                                                Age
                                                <br /><strong>26</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>October 1</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Petite</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>5&rsquo;5</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                        <div class="member-perks">
                                            <p>
                                                Best Feature
                                                <br /><strong>Lips</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>College Degree</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Sales</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$50,000&mdash;75,000K</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                    </div> <!-- .clearfix -->
                                    <div class="members-blue-line"><span><a href="<?= $this->lurl('girl/more') ?>" class="link-more">Tell Me More</a></span></div>
                                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/personal-video.jpg" alt="" />
                                        <span class="play-icon-large"></span>
                                    </a>
                                </div> <!-- .members-blue -->
                            </div> <!-- #members-content-right -->
                        </div> <!-- .clearfix -->
                        <div class="member-icons ib-list ib-middle">
                            <a href="#" class="m-link-message">Message</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-hotlist">Favorite</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-bookmark">Bookmark</a>
                            -->
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-chat">Chat</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-vote">Vote</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-surprise">Surprise</a>
                            -->
                        </div> <!-- .member-icons -->
                        <div class="member-abuse-actions">
                            <a href="#">Block</a>
                            <a href="#">Report</a>
                        </div>
                        <div class="ad-area">
                            <div class="ad"><img src="<?= $this->baseUrl() ?>/images/clipart/ad-1.jpg" alt="" /></div>
                        </div>
                    </div> <!-- #members-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>