<?php $this->getHeader($this->title, '', 1) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <?php $this->getTopSidebar() ?>
            <div id="members-content-wrap">
                <?php $this->getUsersNav() ?>
                <div class="clearfix">
                    <div id="members-content">
                        <div class="clearfix">
                            <div id="members-content-left">
                                <div id="members-content-left-top">
                                    <h2>
                                        scott_1978
                                        <span class="member-age">31 Years</span>
                                    </h2>
                                    <div>
                                        Torrance, CA
                                        <span class="sep-bull">&bull;</span>
                                        Last Login: 3 hours ago
                                    </div>
                                </div> <!-- #members-content-left-top -->
                                <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fermentum ipsum.</h4>
                                <div class="member-big-photo"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-big.jpg" alt="" class="lock" /></div>
                                <div class="member-photos-slider">
                                    <a href="#" class="arrow-prev mps-prev"></a>
                                    <a href="#" class="arrow-next mps-next"></a>
                                    <div class="slider-in">
                                        <div class="slider-in-2 clearfix">
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-1.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-2.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-3.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-4.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-1.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-2.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-3.jpg" alt="" class="block" /></a>
                                            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-man-4.jpg" alt="" class="block" /></a>
                                        </div> <!-- .mts-in-2 -->
                                    </div> <!-- .members-top-slider-in -->
                                </div> <!-- .member-photos-slider -->
                                <h4>About Me</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque</p>
                                <hr />
                                <h4>I&rsquo;m Looking For</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque</p>
                            </div> <!-- #members-content-left -->
                            <div id="members-content-right">
                                <div class="members-blue">
                                    <h3>Personal Details</h3>
                                    <div class="clearfix">
                                        <div class="member-perks">
                                            <p>
                                                Age
                                                <br /><strong>46</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>February 20</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Athletic</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>6&rsquo;2</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                        <div class="member-perks">
                                            <p>
                                                Best Asset
                                                <br /><strong>Brain</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>MBA</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Technology</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$500&mdash;1MK</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                    </div> <!-- .clearfix -->
                                    <div class="members-blue-line"><span><a href="#" class="link-more">Tell Me More</a></span></div>
                                    <h3>10 Things You Should<br />Know About Me</h3>
                                    <div class="clearfix">
                                        <div class="member-perks">
                                            <p>
                                                Righty or Lefty?
                                                <br /><strong>Righty</strong>
                                            </p>
                                            <p>
                                                Morning or Night Person?
                                                <br /><strong>Morning</strong>
                                            </p>
                                            <p>
                                                Favorite Late Night Snack
                                                <br /><strong>Popcorn</strong>
                                            </p>
                                            <p>
                                                Chocolate or Vanilla?
                                                <br /><strong>Chocolate Ice Cream</strong>
                                            </p>
                                            <p>
                                                Favorite Movie
                                                <br /><strong>Easy Rider</strong>
                                            </p>
                                            <p>
                                                Boxers or Briefs?
                                                <br /><strong>Boxers</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                        <div class="member-perks">
                                            <p>
                                                5 things I can&rsquo;t live without
                                                <br /><strong>Cell Phone, Milkshakes, DVR, My kids, Lazy Sundays</strong>
                                                <br /><strong>One day soon I plan to Learn how to sail</strong>
                                            </p>
                                            <p>
                                                Favorite place in the World
                                                <br /><strong>Spain</strong>
                                            </p>
                                            <p>
                                                My Ideal Woman should
                                                <br /><strong>Love dogs</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                    </div> <!-- .clearfix -->
                                </div> <!-- .members-blue -->
                                <h4>Our History</h4>
                                <div>
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1">damac713</div>
                                        <div class="mh-col-2">Viewed</div>
                                        <div class="mh-col-3">May 20</div>
                                    </div> <!-- .members-history-row clearfix -->
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1">Your activity</div>
                                        <div class="mh-col-2">You Kissed</div>
                                        <div class="mh-col-3">May 18</div>
                                    </div> <!-- .members-history-row clearfix -->
                                    <div class="members-history-row clearfix">
                                        <div class="mh-col-1"></div>
                                        <div class="mh-col-2">You Kissed</div>
                                        <div class="mh-col-3">May 18</div>
                                    </div> <!-- .members-history-row clearfix -->
                                </div>
                            </div> <!-- #members-content-right -->
                        </div> <!-- .clearfix -->
                        <div class="member-icons ib-list ib-middle">
                            <a href="#" class="m-link-message">Message</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-hotlist">Favorite</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-bookmark">Bookmark</a>
                            -->
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-chat">Chat</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-vote">Vote</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-surprise">Surprise</a>
                            -->
                        </div> <!-- .member-icons -->
                        <div class="member-abuse-actions">
                            <a href="#">Block</a>
                            <a href="#">Report</a>
                        </div>
                    </div> <!-- #members-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?= $this->getFooter() ?>