<?php $this->getHeader($this->title, '', 1) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <?php $this->getTopSidebar() ?>
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="members-content">
                        <div class="members-list-head clearfix">
                            <div class="ld"><h1>our members</h1></div>
                            <div class="rd">
                                <label for="memhead-1">Sort by</label>
                                <div class="memhead-sort">
                                    <select id="memhead-1">
                                        <option>Newest Members</option>
                                        <option>Oldest Members</option>
                                    </select>
                                </div>
                            </div>
                        </div> <!-- .members-list-head -->
                        <div class="pagination clearfix">
                            <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                            <div class="ib-list rd">
                                <a href="#" class="page active">1</a>
                                <a href="#" class="page">2</a>
                                <a href="#" class="page">3</a>
                            </div>
                        </div> <!-- .pagination -->
                        <div class="ib-list members-list">
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-1.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_<br />789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-2.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-3.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-4.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-5.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-6.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-7.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-8.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-9.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-10.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-11.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                            <div class="ib-block">
                                <div class="member-photo-wrap">
                                    <img src="<?= $this->baseUrl() ?>/images/clipart/member-12.jpg" alt="" class="block" />
                                    <div class="member-screen-name"><span>Ver&oacute;nica_789</span></div>
                                </div>
                                <div class="member-info clearfix">
                                    <div class="rd"><a href="<?= $this->lurl('girl') ?>" class="btn btn-grey">See Profile</a></div>
                                    <div class="ld">
                                        22 years old
                                        <br />New York, US
                                        <br /><span class="member-list-status online">Online Now</span>
                                    </div>
                                </div> <!-- .clearfix -->
                            </div> <!-- .ib-block -->
                        </div> <!-- .members-list -->
                        <div class="pagination clearfix">
                            <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                            <div class="ib-list rd">
                                <a href="#" class="page active">1</a>
                                <a href="#" class="page">2</a>
                                <a href="#" class="page">3</a>
                            </div>
                        </div> <!-- .pagination -->
                    </div> <!-- #members-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>