<?php $this->getHeader($this->title, '', 1) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <?php $this->getTopSidebar() ?>
            <div id="members-content-wrap">
                <?php $this->getUsersNav() ?>
                <div class="clearfix">
                    <div id="members-content">
                        <div class="members-list-head clearfix">
                            <div class="ld"><h1>Tell me more</h1></div>
                            <div class="rd">
                                <ul class="member-head-tabs clearfix">
                                    <li class="active"><a href="<?= $this->lurl('girl/about') ?>">About Me<span class="mht-tip"></span></a></li>
                                    <li><a href="<?= $this->lurl('girl/lookbook') ?>">My Lookbook<span class="mht-tip"></span></a></li>
                                </ul>
                            </div>
                        </div> <!-- .members-list-head -->
                        <div class="clearfix content-after-subnav">
                            <div id="members-content-left">
                                <p><img src="<?= $this->baseUrl() ?>/images/clipart/tell-me-more-1.jpg" alt="" /></p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque.</p>
                                <p class="ra"><a href="#" class="link-more">More</a></p>
                                <hr />
                                <h3>Double dare</h3>
                                <p>
                                    <a href="#" class="link-video">
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/tell-me-more-2.jpg" alt="" />
                                        <span class="play-icon-1">Play Video</span>
                                    </a>
                                </p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque.</p>
                                <p class="ra"><a href="#" class="link-more">More</a></p>
                            </div> <!-- #members-content-left -->
                            <div id="members-content-right">
                                <div class="members-blue">
                                    <h3>Personal Details</h3>
                                    <div class="clearfix">
                                        <div class="member-perks">
                                            <p>
                                                Age
                                                <br /><strong>26</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>October 1</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Petite</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>5&rsquo;5</strong>
                                            </p>
                                            <p>
                                                Age
                                                <br /><strong>26</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>October 1</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Petite</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>5&rsquo;5</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                        <div class="member-perks">
                                            <p>
                                                Best Feature
                                                <br /><strong>Lips</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>College Degree</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Sales</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$50,000&mdash;75,000K</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                            <p>
                                                Best Feature
                                                <br /><strong>Lips</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>College Degree</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Sales</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$50,000&mdash;75,000K</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                    </div> <!-- .clearfix -->
                                    <div class="members-blue-line"><span>&nbsp;</span></div>
                                    <h3>Secrets</h3>
                                    <div class="clearfix">
                                        <div class="member-perks">
                                            <p>
                                                Age
                                                <br /><strong>26</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>October 1</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Petite</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>5&rsquo;5</strong>
                                            </p>
                                            <p>
                                                Age
                                                <br /><strong>26</strong>
                                            </p>
                                            <p>
                                                Birthdate
                                                <br /><strong>October 1</strong>
                                            </p>
                                            <p>
                                                Race
                                                <br /><strong>White</strong>
                                            </p>
                                            <p>
                                                Body Type
                                                <br /><strong>Petite</strong>
                                            </p>
                                            <p>
                                                Height
                                                <br /><strong>5&rsquo;5</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                        <div class="member-perks">
                                            <p>
                                                Best Feature
                                                <br /><strong>Lips</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>College Degree</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Sales</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$50,000&mdash;75,000K</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                            <p>
                                                Best Feature
                                                <br /><strong>Lips</strong>
                                            </p>
                                            <p>
                                                Education
                                                <br /><strong>College Degree</strong>
                                            </p>
                                            <p>
                                                Occupation
                                                <br /><strong>Sales</strong>
                                            </p>
                                            <p>
                                                Income
                                                <br /><strong>$50,000&mdash;75,000K</strong>
                                            </p>
                                            <p>
                                                Personality Type
                                                <br /><strong>High Energy</strong>
                                            </p>
                                        </div> <!-- .member-perks -->
                                    </div> <!-- .clearfix -->
                                </div> <!-- .members-blue -->
                            </div> <!-- #members-content-right -->
                        </div> <!-- .clearfix -->
                        <div class="member-icons ib-list ib-middle">
                            <a href="#" class="m-link-message">Message</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-hotlist">Favorite</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-bookmark">Bookmark</a>
                            -->
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-chat">Chat</a>
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-vote">Vote</a>
                            <!--
                            <span class="member-icons-sep">&bull;</span>
                            <a href="#" class="m-link-surprise">Surprise</a>
                            -->
                        </div> <!-- .member-icons -->
                        <div class="member-abuse-actions">
                            <a href="#">Block</a>
                            <a href="#">Report</a>
                        </div>
                    </div> <!-- #members-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>