<?php $this->getHeader($this->title, '', 1) ?>
<div id="hot-shot-wrap" class="wide-centered-image">
    <div class="backstretch" data-image="<?= $this->baseUrl() ?>/images/clipart/hotshot.jpg"></div>
    <div class="more-info">
        <div class="line-hotshot"></div>
        <h1>MELISSA</h1>
        <div class="line-hotshot"></div>
        <p><strong>• 21 Years •</strong></p>
        <div class="line-hotshot-no-star"></div>
        <p>Torrance, CA</p>
        <div class="hotshot-bottom">
            <a href="<?= $this->lurl('girl/about') ?>" class="hs-about-me"><span>About Me</span></a>
            <a href="<?= $this->lurl('girl/lookbook') ?>" class="hs-lookbook"><span>My LookBook</span></a>
        </div>
        <div class="more-info-shadow"></div>
    </div> <!-- .more-info -->
    <div class="photographed-by">
        <div class="photographed-by-in">
            <div class="photographed-by-1">photographed by</div>
            <div class="photographed-by-2">Derek Kattela</div>
        </div>
    </div>
    <div class="hot-shot-slider-wrap">
        <div class="in">
            <div class="hot-slider-ttl">
                <h2>Other members</h2>
                <div class="hs-ttl-l"></div>
                <div class="hs-ttl-r"></div>
            </div>
            <a href="#" class="hot-shot-nav prev"></a>
            <a href="#" class="hot-shot-nav next"></a>
            <div class="hot-shot-slider">
                <div class="hot-shot-slider-in clearfix">
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-1.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-2.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-3.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-4.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-5.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-6.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-7.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                    <a href="#">
                        <span class="hot-shot-slide-pic"><img src="images/clipart/model-8.jpg" alt="" /></span>
                        <span class="hot-shot-slide-name">Marissa</span>
                    </a>
                </div>
            </div>
        </div> <!-- .in -->
    </div> <!-- .hot-shot-slider-wrap -->
</div> <!-- #hot-shot-wrap -->
<?php $this->getFooter() ?>