<ul class="ib-list">
    <li class="active"><a href="#"><span>Dashboard</span></a></li>
    <li><a href="#"><span>Members</span></a></li>
    <li><a href="#"><span>Hot 100</span></a></li>
    <li><a href="#"><span>Videos</span></a></li>
    <li><a href="#"><span>Gallery</span></a></li>
    <li><a href="#"><span>Parties<br />&amp; Events</span></a></li>
    <li><a href="#"><span>The<br />Good Life</span></a></li>
    <li><a href="#"><span>More</span></a></li>
</ul>