<div id="members-top" class="ib-list">
    <div class="ib-block">
        <h3>Online Now</h3>
        <div class="members-top-block-content mtbc-white">
            <div class="members-top-slider">
                <a href="#" class="mts-prev arrow-prev"></a>
                <a href="#" class="mts-next arrow-next"></a>
                <div class="slider-in">
                    <div class="slider-in-2 clearfix">
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-1.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-2.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-3.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-1.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-2.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-3.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-1.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-2.jpg" alt="" class="block" /></a>
                        <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-3.jpg" alt="" class="block" /></a>
                    </div> <!-- .mts-in-2 -->
                </div> <!-- .members-top-slider-in -->
            </div> <!-- .members-top-slider -->
        </div>
    </div> <!-- .ib-block -->
    <div class="ib-block">
        <h3>Today&rsquo;s Girl</h3>
        <div class="members-top-block-content mtbc-white">
            <a href="#"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-4.jpg" alt="" class="block" /></a>
        </div>
    </div> <!-- .ib-block -->
    <div class="ib-block">
        <h3>Top Videos</h3>
        <div class="members-top-block-content mtbc-white">
            <a href="#" class="link-video">
                <img src="<?= $this->baseUrl() ?>/images/clipart/photo-5.jpg" alt="" />
                <span class="play-icon-small"></span>
            </a>
        </div>
    </div> <!-- .ib-block -->
    <div class="ib-block">
        <h3>Vote Now</h3>
        <div class="members-top-block-content">
            <img src="<?= $this->baseUrl() ?>/images/clipart/bgr-vote-now.jpg" alt="" class="block" />
            <div class="mtbc-over">
                <strong>Hot 100 Vote</strong>
                <br />16 Hours Left
                <br /><a href="#" class="btn btn-blue">Vote Now</a>
            </div> <!-- .mtbc-over -->
        </div>
    </div> <!-- .ib-block -->
    <div class="ib-block">
        <h3>New This Week</h3>
        <div class="members-top-block-content">
            <img src="<?= $this->baseUrl() ?>/images/clipart/bgr-new-this-week.jpg" alt="" class="block" />
            <div class="mtbc-over">
                <strong>Weekly Model Mates<br />Newsletter</strong>
                <br /><a href="#" class="btn btn-blue">Sign Up Now</a>
            </div> <!-- .mtbc-over -->
        </div>
    </div> <!-- .ib-block -->
</div> <!-- #members-top -->