<div id="members-content-top" class="clearfix">
    <div class="mct-nav" id="mct-left">
        <div class="mct-in">
            <a href="<?= $this->lurl('girl') ?>" class="link-prev">Prev</a>
            <a href="<?= $this->lurl('girl') ?>"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-prev.jpg" alt="" class="block" /></a>
        </div>
    </div>
    <div class="mct-nav" id="mct-right">
        <div class="mct-in">
            <a href="<?= $this->lurl('girl') ?>"><img src="<?= $this->baseUrl() ?>/images/clipart/photo-next.jpg" alt="" class="block" /></a>
            <a href="<?= $this->lurl('girl') ?>" class="link-next">Next</a>
        </div>
    </div>
    <h1>samantha_1985</h1>
    <p>Torrance, California</p>
</div> <!-- #members-content-top -->