<?php $this->getHeader($this->title, 'page-video', 3) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <div class="video-content-top clearfix">
                <h1 class="ttl-primary ld">videos</h1>
                <!--
                <div class="rd">
                    <form>
                        <div class="filter-group">
                            <label for="filter-state">State</label>
                            <div class="fg-field">
                                <select id="filter-state">
                                    <option>California</option>
                                    <option>New York</option>
                                </select>
                            </div> <!-- .fg-field --*>
                        </div> <!-- .filter-group --*>
                        <div class="filter-group">
                            <label for="filter-sort-by">Sort by</label>
                            <div class="fg-field">
                                <select id="filter-sort-by">
                                    <option>Most Popular</option>
                                    <option>Least Popular</option>
                                </select>
                            </div> <!-- .fg-field --*>
                        </div> <!-- .filter-group --*>
                    </form>
                </div> <!-- .rd --*>
                -->
            </div> <!-- .video-content-top -->
            <div class="pagination clearfix">
                <!--
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
                -->
            </div> <!-- .pagination -->
            <div class="ib-list videos-list"> 
                <?php foreach($this->videos as $video): ?>
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/'.$video->id) ?>" class="link-video">
                        <?= $video->getThumbnail('thumbmed', 265, 185) ?>
                        <span class="play-icon-xl"></span>
                        <span class="video-duration"><?= $video->duration ?></span>
                    </a>
                    <div class="video-item-text">
                        <?php if($video->object_type == 'hot100'): ?>
                        <a href="<?= $this->lurl('videos/'.$video->id) ?>" class="video-item-ttl"><?= $video->getHot100('username') ?></a>
                        <?php else: ?>
                        <a href="<?= $this->lurl('videos/'.$video->id) ?>" class="video-item-ttl"><?= $video->title ?></a>
                        <?php endif ?>
                        <div class="video-item-date"><?= $video->getDate('ago') ?></div>
                    </div>
                </div> <!-- .ib-block -->
                <?php endforeach ?>
            </div> <!-- .videos-list -->
            <div class="pagination clearfix no-border">
                <!--
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
                -->
            </div> <!-- .pagination -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>