<?php $this->getHeader($this->title, 'page-video', 3) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <div class="video-content-top clearfix">
                <h1 class="ttl-primary ld">videos</h1>
                <div class="rd">
                    <form>
                        <div class="filter-group">
                            <label for="filter-state">State</label>
                            <div class="fg-field">
                                <select id="filter-state">
                                    <option>California</option>
                                    <option>New York</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                        <div class="filter-group">
                            <label for="filter-sort-by">Sort by</label>
                            <div class="fg-field">
                                <select id="filter-sort-by">
                                    <option>Most Popular</option>
                                    <option>Least Popular</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                    </form>
                </div> <!-- .rd -->
            </div> <!-- .video-content-top -->
            <div class="pagination clearfix">
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
            <div class="ib-list videos-list"> 
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-1.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-2.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-3.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-4.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-5.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-6.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-7.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-8.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="<?= $this->lurl('videos/123456') ?>" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-cat-9.jpg" alt="" />
                        <span class="play-icon-xl"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="<?= $this->lurl('username') ?>" class="video-item-ttl">Ximena_654</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
            </div> <!-- .videos-list -->
            <div class="pagination clearfix no-border">
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>