<?php $this->getHeader($this->title, '', 5) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <h1 class="ttl-primary party-detail-ttl">Summer party</h1>
            <div class="clearfix">
                <div class="party-detail-left">
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Event</div>
                        <div class="pdl-data">All White Party</div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Date</div>
                        <div class="pdl-data">Saturday, April 26th, 2014</div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Time</div>
                        <div class="pdl-data">8:00 pm - 1:00 am</div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Location</div>
                        <div class="pdl-data">Green Coast Hotel, San Francisco, CA</div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Description</div>
                        <div class="pdl-data">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id neque velit, a rutrum lectus. Nam a felis erat. Nunc est felis, vehicula eget elementum et, ultrices eu lectus. Sed iaculis imperdiet arcu eleifend accumsan. Integer tempor vestibulum euismod. Morbi gravida dapibus enim. Etiam at metus tristique magna porttitor ultrices. Vestibulum massa diam, molestie sit amet fringilla eu, fermentum ac dui. Fusce non gravida neque</p>
                            <div class="clearfix">
                                <div class="pdl-price-block">
                                    <div class="pdl-price-unit">
                                        <div class="pdl-pu-1">$20</div>
                                        <div class="pdl-pu-2">per person</div>
                                    </div>
                                    <div class="pdl-pu-text">General<br />Admission</div>
                                </div>
                                <div class="pdl-price-block">
                                    <div class="pdl-price-unit">
                                        <div class="pdl-pu-1">$35</div>
                                        <div class="pdl-pu-2">per person</div>
                                    </div>
                                    <div class="pdl-pu-text">VIP (Complimentary<br />Drinks)</div>
                                </div>
                            </div> <!-- .clearfix -->
                        </div>
                    </div> <!-- .pdl-row -->
                </div> <!-- .party-detail-left -->
                <div class="party-detail-right">
                    <div class="pdl-r-image"><img src="<?= $this->baseUrl() ?>/images/clipart/event-details.jpg" alt="" class="block" /></div>
                    <p>
                        <a href="#" class="btn btn-blue">Register</a>
                        <a href="#" class="btn btn-grey">Invite a Friend</a>
                        <a href="#" class="link-more">View Event Photos</a>
                    </p>
                </div> <!-- .party-detail-right -->
            </div> <!-- .clearfix -->
        </div> <!-- .video-category-content -->

        <div class="video-category-content">
            <div class="video-content-top clearfix">
                <h1 class="ttl-primary ld">other Parties &amp; Events</h1>
            </div> <!-- .video-content-top -->
            <div class="pe-sub-title">
            </div> <!-- .pe-sub-title -->
            <div class="ib-list events-list"> 
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-1.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-2.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-3.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
            </div> <!-- .events-list -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>