<?php $this->getHeader($this->title, '', 5) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <?php $this->getTopSidebar() ?>
            <div id="members-content-wrap">
                <div id="events-content-top" class="clearfix">
                    <h1 class="ttl-primary ld">Parties &amp; Events</h1>
                    <div class="rd">
                        <form>
                            <div class="filter-group">
                                <label for="filter-state">State</label>
                                <div class="fg-field">
                                    <select id="filter-state">
                                        <option>California</option>
                                        <option>New York</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                            <div class="filter-group">
                                <label for="filter-month">Month</label>
                                <div class="fg-field">
                                    <select id="filter-month">
                                        <option>January</option>
                                        <option>February</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                            <div class="filter-group">
                                <label for="filter-activity">Activity</label>
                                <div class="fg-field">
                                    <select id="filter-activity">
                                        <option>Major Events</option>
                                        <option>Minor Events</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                        </form>
                    </div> <!-- .rd -->
                </div> <!-- #events-content-top -->
                <div class="clearfix">
                    <div id="members-content">
                        <div class="clearfix" id="ec-top">
                            <div id="ec-content">
                                <div class="pagination clearfix no-border no-margin-top">
                                    <div class="ld">Showing 1-9 of 30 Results</div>
                                    <div class="ib-list rd">
                                        <a href="#" class="page active">1</a>
                                        <a href="#" class="page">2</a>
                                        <a href="#" class="page">3</a>
                                    </div>
                                </div> <!-- .pagination -->
                                <div class="ib-list events-list small"> 
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <div class="event-time">
                                            <div class="event-time-month">APR</div>
                                            <div class="event-time-day">26</div>
                                        </div>
                                        <div class="event-pic"><img src="images/clipart/event-1.jpg" alt="" class="block" /></div>
                                        <div class="event-item-in">
                                            <div class="event-name">Summer Party</div>
                                            <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                                            <div class="event-actions ib-list">
                                                <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                                                <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                                            </div>
                                        </div>
                                    </div> <!-- .ib-block -->
                                </div> <!-- .events-list -->
                            </div> <!-- #ec-content -->
                            <div id="ec-sidebar">
                                <div class="ec-ad"><img src="images/clipart/ad-3.jpg" alt="" class="block" /></div>
                                <div class="ec-ad"><img src="images/clipart/ad-3.jpg" alt="" class="block" /></div>
                            </div> <!-- #ec-sidebar -->
                        </div> <!-- .clearfix -->
                        <div class="ib-list event-buttons">
                            <!--<div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Submit an Event</a></div>
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">View Calendar</a></div>-->
                            <div class="ib-block"><a href="<?= $this->lurl('events/all') ?>" class="btn btn-blue">More Events</a></div>
                        </div> <!-- .ib-list -->
                    </div> <!-- #members-content -->

                    <?php $this->getSidebar(array('favorites', 'search', 'account')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>