<?php $this->getHeader($this->title, '', 5) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <h1 class="ttl-primary party-detail-ttl"><?= $this->event->title ?></h1>
            <div class="clearfix">
                <div class="party-detail-left">
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Event</div>
                        <div class="pdl-data"><?= $this->event->title ?></div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Date</div>
                        <div class="pdl-data"><?= $this->event->getDate('l, F jS, Y') ?></div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Time</div>
                        <div class="pdl-data"><?= $this->event->getTime() ?></div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Location</div>
                        <div class="pdl-data"><?= $this->event->location ?></div>
                    </div> <!-- .pdl-row -->
                    <div class="pdl-row clearfix">
                        <div class="pdl-lbl">Description</div>
                        <div class="pdl-data">
                            <p><?= nl2br($this->event->description) ?></p>
                            <?php $covers = $this->event->getCovers() ?>
                            <?php if(count($covers) > 0): ?>
                            <div class="clearfix">
                                <?php foreach($covers as $c): ?>
                                <div class="pdl-price-block">
                                    <div class="pdl-price-unit">
                                        <div class="pdl-pu-1">$<?= number_format($c->price) ?></div>
                                        <div class="pdl-pu-2">per person</div>
                                    </div>
                                    <div class="pdl-pu-text"><?= $c->title ?></div>
                                </div>
                                <?php endforeach ?>
                            </div> <!-- .clearfix -->
                            <?php endif ?>
                        </div>
                    </div> <!-- .pdl-row -->
                </div> <!-- .party-detail-left -->
                <div class="party-detail-right">
                    <div class="pdl-r-image">
                        <?= $this->event->getPicture('thumbbig', 438, 242, 'block') ?>
                    </div>
                    <p>
                        <?php if($this->user === null): ?>
                        <a href="<?= $this->lurl('signup') ?>" class="btn btn-blue">Register</a>
                        <?php else: ?>
                        <a href="#" class="btn js-register btn-blue">Register</a>
                        <?php endif ?>
                        <a href="#" class="btn js-invite btn-grey">Invite a Friend</a>
                        <!--<a href="#" class="link-more">View Event Photos</a> -->
                    </p>
                </div> <!-- .party-detail-right -->
            </div> <!-- .clearfix -->
        </div> <!-- .video-category-content -->

        <div class="video-category-content">
            <div class="video-content-top clearfix">
                <h1 class="ttl-primary ld">other Parties &amp; Events</h1>
            </div> <!-- .video-content-top -->
            <div class="pe-sub-title">
            </div> <!-- .pe-sub-title -->
            <div class="ib-list events-list"> 
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-1.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-2.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-3.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="#" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
            </div> <!-- .events-list -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>