<?php $this->getHeader($this->title, '', 5) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <div class="video-content-top clearfix">
                <h1 class="ttl-primary ld">Parties &amp; Events</h1>
                <div class="rd">
                    <form>
                        <div class="filter-group">
                            <label for="filter-state">State</label>
                            <div class="fg-field">
                                <select id="filter-state">
                                    <option>California</option>
                                    <option>New York</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                        <div class="filter-group">
                            <label for="filter-month">Month</label>
                            <div class="fg-field">
                                <select id="filter-month">
                                    <option>January</option>
                                    <option>February</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                        <div class="filter-group">
                            <label for="filter-activity">Activity</label>
                            <div class="fg-field">
                                <select id="filter-activity">
                                    <option>Major Events</option>
                                    <option>Minor Events</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                    </form>
                </div> <!-- .rd -->
            </div> <!-- .video-content-top -->
            <div class="pe-sub-title">
                <h2>Super Concerts</h2>
            </div> <!-- .pe-sub-title -->
            <div class="pagination clearfix">
                <div class="ld">Showing 1-9 of 30 Results</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
            <div class="ib-list events-list"> 
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-1.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-2.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-3.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-4.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-5.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-6.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-7.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-8.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <div class="event-time">
                        <div class="event-time-month">APR</div>
                        <div class="event-time-day">26</div>
                    </div>
                    <div class="event-pic"><img src="<?= $this->baseUrl() ?>/images/clipart/event-9.jpg" alt="" class="block" /></div>
                    <div class="event-item-in">
                        <div class="event-name">Summer Party</div>
                        <div class="event-description">@ AJ&rsquo;s Bar &amp; Grill</div>
                        <div class="event-actions ib-list">
                            <div class="ib-block"><a href="<?= $this->lurl('events/123456') ?>" class="btn btn-blue">Register</a></div>
                            <div class="ib-block"><a href="#" class="btn btn-grey">Invite a Friend</a></div>
                        </div>
                    </div>
                </div> <!-- .ib-block -->
            </div> <!-- .events-list -->
            <div class="pagination clearfix no-border">
                <div class="ld">Showing 1-9 of 30 Results</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>