<?php $this->getHeader($this->title, 'page-video', 4) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div id="members-content-wrap">
            <div class="clearfix">
                <div id="gallery-content-1">
                    <?php foreach($this->gallery->getImages() as $pic): ?>
                    <div class="gallery-main-block">
                        <?= $pic->getImage('','','') ?>
                    </div> <!-- .gallery-main-block -->
                    <?php endforeach ?>
                </div> <!-- #gallery-content-1 -->
                <div id="members-sidebar" class="results-sidebar gallery-sidebar">
                    <div class="gallery-widget">
                        <h2>Gallery</h2>
                        <p>Select a Category</p>
                        <ul>
                            <?php foreach($this->galleries as $g): ?>
                            <li class="<?= ($g->id == $this->gallery->id) ? 'active' : '' ?>"><a href="<?= $this->lurl('galleries/'.$g->id) ?>"><?= $g->title ?></a></li>
                            <?php endforeach ?>
                        </ul>
                    </div> <!-- .gallery-widget -->
                </div> <!-- #members-sidebar -->
            </div>
        </div> <!-- #members-content-wrap -->

    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>