<?php $this->getHeader($this->title, 'page-video', 3) ?>
<div id="videos-home-top">
    <div class="in">
        <div class="ib-list">
            <div class="ib-block">
                <div class="vht-pic-wrap"><img src="images/clipart/video-girl-1.png" alt="" /></div>
                <h2>Hot 100</h2>
                <p>Lorem ipsum dolor sit amet, conse ctetur adipiscing elit</p>
                <p><a href="<?= $this->lurl('hot100/videos') ?>" class="btn btn-blue">Watch Hot 100 Videos</a></p>
            </div> <!-- .ib-block -->
            <div class="ib-block">
                <div class="vht-pic-wrap"><img src="images/clipart/video-girl-2.png" alt="" /></div>
                <h2>Double Dare</h2>
                <p>Lorem ipsum dolor sit amet, conse ctetur adipiscing elit</p>
                <p><a href="<?= $this->lurl('videos/category/all') ?>" class="btn btn-blue">Watch All Double Dare Videos</a></p>
            </div> <!-- .ib-block -->
            <div class="ib-block">
                <div class="vht-pic-wrap"><img src="images/clipart/video-girl-3.png" alt="" /></div>
                <h2>Watch All</h2>
                <p>Lorem ipsum dolor sit amet, conse ctetur adipiscing elit</p>
                <p><a href="<?= $this->lurl('videos/category/all') ?>" class="btn btn-blue">Watch Funny Girls Videos</a></p>
            </div> <!-- .ib-block -->
        </div> <!-- .ib-list -->
    </div> <!-- .in -->
</div> <!-- #videos-home-top -->
<div class="in white-box-1" id="videos-home-main-wrap">
    <div id="videos-home-main" class="clearfix">
        <div class="videos-right">
            <h1 class="ttl-primary">upcoming events</h1>
            <div class="ib-list videos-home-list">
                <?php foreach($this->events as $event): ?>
                <div class="ib-block">
                    <div class="clearfix">
                        <?= $event->getPicture('thumbsmall', 109, 89, 'ld'); ?>
                        <div class="event-small-descr">
                            <p><strong><?= $event->title ?></strong></p>
                            <p><?= $event->getDate('F j, Y') ?></p>
                            <p><a href="<?= $this->lurl('events/'.$event->id) ?>" class="link-more">Read more</a></p>
                        </div> <!-- .event-small-descr -->
                    </div> <!-- .clearfix -->
                </div> <!-- .ib-block -->
                <?php endforeach ?>
            </div> <!-- .videos-home-list -->
        </div> <!-- .videos-right -->
        <div class="videos-left">
            <h1 class="ttl-primary">VIDEO CATEGORIES</h1>
            <ul>
                <?php foreach($this->categories as $cat): ?>
                <li><a href="<?= $this->lurl('videos/category/'.$cat->permalink) ?>"><?= $cat->name ?></a></li>
                <?php endforeach ?>
            </ul>
            <p><a href="<?= $this->lurl('videos/category/all') ?>" class="btn btn-blue">See All Videos</a></p>
        </div> <!-- .videos-left -->
    </div> <!-- #videos-home-main -->
</div> <!-- #videos-home-main-wrap -->
<?php $this->getFooter() ?>