<?php $this->getHeader($this->title, 'page-video', 6) ?>
<div class="sp-wrap">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="good-life-content">
                        <h1 class="ttl-primary">the good life</h1>
                        <div class="clearfix glc-main">
                            <div class="glc-main-left">
                                <?php $pictures = $this->listing->getPictures() ?>
                                <?php if(count($pictures) > 0): ?>
                                <?= $pictures[0]->getImage('thumbmed', 357, 263, 'block'); ?>
                                <div class="ib-list good-life-detail-pics">
                                    <?php foreach($pictures as $i => $pic): ?>
                                    <?php if($i != 0): ?>
                                    <div class="ib-block"><a href="<?= $pic->getUrl() ?>"><?= $pic->getImage('thumbmed', 178, 'auto', 'block') ?></a></div>
                                    <?php endif ?>
                                    <?php endforeach ?>
                                </div> <!-- .good-life-detail-pics -->
                                <?php endif ?>
                            </div> <!-- .glc-main-left -->
                            <div class="glc-main-right">
                                <p><span class="tag-top-10">TOP 10</span></p>
                                <h3><?= $this->listing->getCategoryLabel() ?></h3>
                                <h2><?= $this->listing->title ?></h2>
                                <p class="good-life-location"><?= $this->listing->city ?>, <?= $this->listing->state ?></p>
                                <div class="good-life-style">
                                    <?= $this->listing->type ?>
                                </div>
                                <p><?= nl2br($this->listing->description) ?></p>
                                <hr />
                                <p>
                                    <strong>Parking Info</strong>
                                    <br /><?= ($this->listing->parking == 1) ? 'Yes' : 'No' ?>
                                </p>
                                <p>
                                    <strong>Address</strong>
                                    <br /><?= nl2br($this->listing->address) ?>
                                </p>
                                <p>
                                    <strong>Telephone</strong>
                                    <br /><?= $this->listing->phone ?>
                                </p>
                                <p>
                                    <br />
                                    <!--<a href="#" class="btn btn-blue">Menu</a>&nbsp;&nbsp;&nbsp;-->
                                    <?php if($this->user !== null): ?>
                                    <a href="#" class="js-register btn btn-blue">Reserve Now</a>
                                    <?php else: ?>
                                    <a href="<?= $this->lurl('signup') ?>" class="btn btn-blue">Reserve Now</a>
                                    <?php endif ?>
                                </p>
                            </div> <!-- .glc-main-right -->
                        </div> <!-- .glc-main -->
                        <div class="ad"><img src="<?= $this->baseUrl() ?>/images/clipart/ad-4.jpg" alt="" /></div>
                    </div> <!-- #good-life-content -->

                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>