<?php $this->getHeader($this->title, 'page-video', 6) ?>
<div class="sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content no-padding">
            <div class="good-life-home-top">
                <div class="good-life-home-top-1">
                    <h1 class="ttl-primary">the good life</h1>
                    <?php $listing = $this->listings[0] ?>
                    <div class="clearfix glht-1-1">
                        <div class="glht1-left">
                            <div class="glht1-left-pic">
                                <?= $listing->getMainPicture('thumbbig', 'block') ?>
                                <span class="good-life-result-num">1</span>
                            </div>
                        </div> <!-- .glht1-left -->
                        <div class="glht1-right">
                            <p><span class="tag-top-10">TOP 10</span></p>
                            <h3><?= $listing->getCategoryLabel() ?></h3>
                            <h2><?= $listing->title ?></h2>
                            <p class="good-life-location"><?= $listing->city ?>, <?= $listing->state ?></p>
                            <div class="good-life-style">
                                <?= $listing->type ?>
                            </div>
                            <p><?= nl2br($listing->description) ?></p>
                            <p><br /><a href="<?= $this->lurl('life/'.$listing->id) ?>" class="btn btn-blue">Explore</a></p>
                        </div> <!-- .glht1-right -->
                    </div> <!-- .clearfix -->
                    <div class="glht1-nav">
                        <ul class="ib-list">
                            <?php foreach($this->categories as $c): ?>
                            <li class="ib-block <?= $c->id == $this->category ? 'active' : '' ?>"><a href="?cat=<?= $c->id ?>"><?= $c->title ?></a></li>
                            <?php endforeach ?>
                        </ul>
                    </div> <!-- .glht1-nav -->
                </div> <!-- .good-life-home-top-1 -->
                <div class="good-life-home-top-2 clearfix">
                    <h2 class="ttl-primary ld">Search by</h2>
                    <div class="rd">
                        <form>
                            <div class="filter-group">
                                <label for="filter-state">State</label>
                                <div class="fg-field">
                                    <select id="filter-state">
                                        <option>California</option>
                                        <option>New York</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                            <div class="filter-group">
                                <label for="filter-city">City</label>
                                <div class="fg-field">
                                    <select id="filter-city">
                                        <option>January</option>
                                        <option>February</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                            <div class="filter-group">
                                <label for="filter-category">Category</label>
                                <div class="fg-field">
                                    <select id="filter-category">
                                        <option>Major Events</option>
                                        <option>Minor Events</option>
                                    </select>
                                </div> <!-- .fg-field -->
                            </div> <!-- .filter-group -->
                            <div class="filter-group glht2-submit-wrap"><a href="#" class="btn btn-blue">Search</a></div>
                        </form>
                    </div>
                </div> <!-- .good-life-home-top-2 -->
            </div> <!-- .good-life-home-top -->
            <div class="good-life-home-results">
                <div class="ib-list good-life-list">
                    <?php unset($this->listings[0]) ?>
                    <?php foreach($this->listings as $i => $list): ?>
                    <a href="<?= $this->lurl('life/'.$list->id) ?>" class="ib-block">
                        <span class="good-life-result-pic">
                            <span class="good-life-result-num"><?= $i + 1 ?></span>
                            <span class="good-life-result-name"><span><?= $list->title ?></span></span>
                            <?= $list->getMainPicture('thumbsmall', 'block') ?>
                        </span>
                        <span class="good-life-result-title"><?= $list->type ?></span>
                    </a> <!-- .ib-block -->
                    <?php endforeach ?>
                </div> <!-- .ib-list -->
            </div> <!-- .good-life-home-results -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>