<?php $this->getHeader($this->title, '', 3) ?>
<div id="video-sub-wrap">
    <div class="in white-box-1">
        <div class="video-category-content">
            <div id="video-detail">
                <h1 class="ttl-primary">Username - Intimate</h1>
                <div class="clearfix">
                    <div id="video-detail-left">
                        <a href="#" class="link-video">
                            <img src="<?= $this->baseUrl() ?>/images/clipart/video-big.jpg" alt="" />
                            <span class="play-icon-1">Play Video</span>
                        </a>
                    </div> <!-- #video-detail-left -->
                    <div id="video-detail-right">
                        <div class="ad"><img src="<?= $this->baseUrl() ?>/images/clipart/ad-2.jpg" alt="" class="block" /></div>
                        <h2 class="ttl-sub-1">Next Video:</h2>
                        <div class="clearfix">
                            <a href="#" class="link-video ld">
                                <img src="<?= $this->baseUrl() ?>/images/clipart/video-next.jpg" alt="" />
                                <span class="play-icon-middle"></span>
                            </a>
                            <div class="next-video-descr">
                                <p>Cinthya Henderson</p>
                                <p><strong>Up Close</strong></p>
                            </div> <!-- .next-video-descr -->
                        </div> <!-- .clearfix -->
                    </div> <!-- #video-detail-right -->
                </div> <!-- .clearfix -->
            </div> <!-- #video-detail -->
            <div class="video-content-top clearfix">
                <h2 class="ttl-primary ld">Hot 100 Video Collection</h2>
                <div class="rd">
                    <form>
                        <div class="filter-group">
                            <label for="filter-state">State</label>
                            <div class="fg-field">
                                <select id="filter-state">
                                    <option>California</option>
                                    <option>New York</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                        <div class="filter-group">
                            <label for="filter-sort-by">Sort by</label>
                            <div class="fg-field">
                                <select id="filter-sort-by">
                                    <option>Most Popular</option>
                                    <option>Least Popular</option>
                                </select>
                            </div> <!-- .fg-field -->
                        </div> <!-- .filter-group -->
                    </form>
                </div> <!-- .rd -->
            </div> <!-- .video-content-top -->
            <div class="pagination clearfix">
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
            <div class="ib-list videos-list small"> 
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-1.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-2.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-3.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-4.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-5.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-6.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-7.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-8.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-9.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-10.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-11.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
                <div class="ib-block">
                    <a href="#" class="link-video">
                        <img src="<?= $this->baseUrl() ?>/images/clipart/video-12.jpg" alt="" />
                        <span class="play-icon-middle"></span>
                        <span class="video-duration">4:05</span>
                    </a>
                    <div class="video-item-text">
                        <a href="#" class="video-item-ttl">Up Close</a>
                        <div class="video-item-date">5 Months Ago</div>
                    </div>
                </div> <!-- .ib-block -->
            </div> <!-- .videos-list -->
            <div class="pagination clearfix no-border">
                <div class="ld">Showing 1-9 of 56 Videos</div>
                <div class="ib-list rd">
                    <a href="#" class="page active">1</a>
                    <a href="#" class="page">2</a>
                    <a href="#" class="page">3</a>
                </div>
            </div> <!-- .pagination -->
        </div> <!-- .video-category-content -->
    </div> <!-- .white-box-1 -->
</div> <!-- #video-sub-wrap -->
<?php $this->getFooter() ?>