    <footer role="contentinfo">
        <div class="clearfix">
            <ul class="list-unstyled list-inline pull-left">
                <li>AVANT &copy; 2013</li>
            </ul>
            <button class="pull-right btn btn-inverse-alt btn-xs hidden-print" id="back-to-top"><i class="fa fa-arrow-up"></i></button>
        </div>
    </footer>
</div> <!-- page-container -->
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/jquery-1.10.2.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/jqueryui-1.10.3.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/bootstrap.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/enquire.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/jquery.cookie.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/jquery.nicescroll.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/codeprettifier/prettify.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/easypiechart/jquery.easypiechart.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/sparklines/jquery.sparklines.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/form-toggle/toggle.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/fullcalendar/fullcalendar.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/form-daterangepicker/daterangepicker.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/form-daterangepicker/moment.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/charts-flot/jquery.flot.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/charts-flot/jquery.flot.resize.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/charts-flot/jquery.flot.orderBars.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/plugins/pulsate/jQuery.pulsate.min.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/placeholdr.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/scripts/uploader.js'></script> 
<script type='text/javascript' src='<?= $this->baseUrl() ?>/adm/js/application.js'></script> 
<?php if(count($this->scripts) > 0): foreach($this->scripts as $src): ?>
<script type='text/javascript' src='<?= $this->baseUrl() ?>/<?= $src ?>'></script> 
<?php endforeach; endif; ?>
</body>
</html>