<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Modelmates | Admin Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Modelmates Dashboard">
    <meta name="author" content="Xubliminal">
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/adm/css/styles.css?=120">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>
    <link href='<?= $this->baseUrl() ?>/adm/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='styleswitcher'> 
    <link href='<?= $this->baseUrl() ?>/adm/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='headerswitcher'> 
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries. Placeholdr.js enables the placeholder attribute -->
    <!--[if lt IE 9]>
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/adm/css/ie8.css">
        <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.1.0/respond.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/adm/plugins/charts-flot/excanvas.min.js"></script>
    <![endif]-->
    <link rel='stylesheet' type='text/css' href='<?= $this->baseUrl() ?>/adm/js/jqueryui.css' /> 
    <link rel='stylesheet' type='text/css' href='<?= $this->baseUrl() ?>/adm/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' /> 
    <link rel='stylesheet' type='text/css' href='<?= $this->baseUrl() ?>/adm/plugins/form-markdown/css/bootstrap-markdown.min.css' /> 
    <link rel='stylesheet' type='text/css' href='<?= $this->baseUrl() ?>/adm/plugins/codeprettifier/prettify.css' /> 
    <link rel='stylesheet' type='text/css' href='<?= $this->baseUrl() ?>/adm/plugins/form-toggle/toggles.css' /> 
</head>
<body class=" ">
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <a id="leftmenu-trigger" class="tooltips" data-toggle="tooltip" data-placement="right" title="Toggle Sidebar"></a>
    <div class="navbar-header pull-left">
        <a class="navbar-brand" href="<?= $this->baseUrl() ?>/admin">MODELMATES</a>
    </div>
    <ul class="nav navbar-nav pull-right toolbar">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle username" data-toggle="dropdown">
            <span class="hidden-xs">Admin <i class="fa fa-caret-down"></i></span></a>
            <ul class="dropdown-menu userinfo arrow">
                <li class="userlinks">
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->baseUrl() ?>/admin/logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</header>
<div id="page-container">
    <!-- BEGIN SIDEBAR -->
    <nav id="page-leftbar" role="navigation">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="acc-menu" id="sidebar">
            <li><a href="<?= $this->baseUrl() ?>/admin/listings"><i class="fa fa-cutlery"></i> <span>The Good Life</span></a></li>
            <li><a href="<?= $this->baseUrl() ?>/admin/events"><i class="fa fa-calendar"></i> <span>Parties and Events</span></a></li>
            <li class="divider"></li>
            <li><a href="javascript:;"><i class="fa fa-th"></i> <span>Layout Options</span> </a>
                <ul class="acc-menu">
                    <li><a href="layout-grid.htm"><span>Grids</span></a>
                    <li><a href="layout-horizontal.htm"><span>Horizontal Navigation</span></a>
                    <li><a href="layout-horizontal2.htm"><span>Horizontal Navigation 2</span></a>
                    <li><a href="layout-fixed.htm"><span>Fixed Boxed Layout</span></a>
                </ul>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </nav>