<?php $this->getHeader($this->title, 'page-black', 2) ?>
<div class="hot-wrap-1">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="more-main-content">
                        <?= $this->partial('partials/hottop.phtml', array('active' => 0)) ?>
                        <div id="hot-100-main">
                            <div id="hot-100-big-vid" class="clearfix">
                                <div class="h100bv-left">
                                    <a href="<?= $this->lurl('video/123') ?>" class="link-video">
                                        <img src="images/clipart/hot-100-video-big.jpg" alt="" />
                                        <span class="play-icon-xxl"></span>
                                    </a>
                                </div> <!-- .h100bv-left -->
                                <div class="h100bv-right">
                                    <ul>
                                        <li><a href="#">
                                                <div><strong>Video 1</strong></div>
                                                <div>Lorem ipsum dolor sit amet.</div>
                                            </a></li>
                                        <li class="active"><a href="#">
                                                <div><strong>Video 2</strong></div>
                                                <div>Lorem ipsum dolor sit amet.</div>
                                            </a></li>
                                        <li><a href="#">
                                                <div><strong>Video 3</strong></div>
                                                <div>Lorem ipsum dolor sit amet.</div>
                                            </a></li>
                                        <li><a href="#">
                                                <div><strong>Video 4</strong></div>
                                                <div>Lorem ipsum dolor sit amet.</div>
                                            </a></li>
                                        <li><a href="#">
                                                <div><strong>Video 5</strong></div>
                                                <div>Lorem ipsum dolor sit amet.</div>
                                            </a></li>
                                    </ul>
                                </div> <!-- .h100bv-right -->
                            </div> <!-- #hot-100-big-vid -->
                            <div id="hot-100-meet-em">
                                <h2 class="ttl-primary ca">meet the top 10</h2>
                                <div class="ib-list">
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">1</span>
                                        <img src="images/clipart/hot-100-xs-1.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">2</span>
                                        <img src="images/clipart/hot-100-xs-2.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">3</span>
                                        <img src="images/clipart/hot-100-xs-3.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">4</span>
                                        <img src="images/clipart/hot-100-xs-4.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">5</span>
                                        <img src="images/clipart/hot-100-xs-5.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">6</span>
                                        <img src="images/clipart/hot-100-xs-6.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">7</span>
                                        <img src="images/clipart/hot-100-xs-7.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">8</span>
                                        <img src="images/clipart/hot-100-xs-8.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">9</span>
                                        <img src="images/clipart/hot-100-xs-9.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                    <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                        <span class="h100-ibl1-no">10</span>
                                        <img src="images/clipart/hot-100-xs-10.jpg" alt="" class="block" />
                                        <span class="h100-ibl1-ttl">
                                            <span class="h100-ibl1-ttl-1">Veronica</span>
                                            <span class="h100-ibl1-ttl-2">San Francisco, CA</span>
                                        </span>
                                    </a> <!-- .ib-block -->
                                </div> <!-- .ib-list -->
                            </div> <!-- #hot-100-gblock -->
                            <div id="hot-100-gblock">
                                <div class="clearfix hot-100-gblock-top">
                                    <h2 class="ttl-primary ld">Hot 100</h2>
                                    <a href="<?= $this->lurl('hot100/models') ?>" class="link-more rd">Cast your Vote Now</a>
                                </div>
                                <div class="ib-list">
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-1.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-2.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-3.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-4.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-5.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                    <div class="ib-block">
                                        <img src="images/clipart/hot-100-small-6.jpg" alt="" class="block" />
                                        <div class="clearfix">
                                            <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                            <div class="ld">
                                                <strong>Veronica</strong>
                                                <br />
                                                1,256 Votes
                                            </div> <!-- .ld -->
                                        </div> <!-- .clearfix -->
                                    </div> <!-- .ib-block -->
                                </div> <!-- .ib-list -->
                            </div> <!-- #hot-100-gblock -->
                        </div> <!-- #hot-100-main -->
                    </div> <!-- #more-main-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>