<?php $this->getHeader($this->title, 'page-black', 2) ?>
<div class="sp-wrap hot-wrap-1">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="more-main-content">
                        <?= $this->partial('partials/hottop.phtml', array('active' => 0)) ?>
                        <div id="hot-100-main">
                            <div class="hot-100-main-list-top clearfix">
                                <h2 class="ld">Vote Now</h2>
                                <div class="rd">
                                    <form>
                                        <div class="filter-group">
                                            <a href="#" class="btn btn-grey">Vote</a>
                                            <a href="#" class="btn btn-grey">Enter</a>
                                            <a href="#" class="btn btn-grey">See All</a>
                                        </div> <!-- .filter-group -->
                                        <div class="filter-group">
                                            <label for="filter-state">Location</label>
                                            <div class="fg-field">
                                                <select id="filter-state">
                                                    <option>California</option>
                                                    <option>New York</option>
                                                </select>
                                            </div> <!-- .fg-field -->
                                        </div> <!-- .filter-group -->
                                    </form>
                                </div>
                            </div> <!-- .hot-100-main-list-top -->
                            <div class="pagination clearfix">
                                <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                                <div class="ib-list rd">
                                    <a href="#" class="page active">1</a>
                                    <a href="#" class="page">2</a>
                                    <a href="#" class="page">3</a>
                                </div>
                            </div> <!-- .pagination -->
                            <div class="ib-list hot-100-main-list">
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">1</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-1.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">2</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-2.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">3</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-3.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">4</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-4.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">5</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-5.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">6</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-6.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">7</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-7.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">8</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-8.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-main-list-pic">
                                        <span class="hot-100-main-list-no">9</span>
                                        <div class="hot-100-main-list-ttl"><span>Katherine_7867</span></div>
                                        <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-9.jpg" alt="" class="block" />
                                    </div> <!-- .hot-100-main-list-pic -->
                                    <div class="clearfix">
                                        <div class="ld hot-100-main-list-bl">San Francisco, CA</div>
                                        <a href="<?= $this->lurl('hot100/models/1234') ?>" class="btn btn-red rd">Vote</a>
                                    </div> <!-- .clearfix -->
                                </div> <!-- .ib-block -->
                            </div> <!-- .hot-100-main-list -->
                            <div class="pagination clearfix">
                                <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                                <div class="ib-list rd">
                                    <a href="#" class="page active">1</a>
                                    <a href="#" class="page">2</a>
                                    <a href="#" class="page">3</a>
                                </div>
                            </div> <!-- .pagination -->
                        </div> <!-- #hot-100-main -->
                    </div> <!-- #more-main-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>
</body>
</html>