<?php $this->getHeader($this->title, 'page-black', 2) ?>
<div class="sp-wrap hot-wrap-1">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="more-main-content">
                        <?= $this->partial('partials/hottop.phtml', array('active' => 1)) ?>
                        <div id="hot-100-main">
                            <div class="hot-100-main-list-top clearfix">
                                <h2 class="ld">Women Profiles</h2>
                                <div class="rd">
                                    <form>
                                        <div class="filter-group">
                                            <span class="vam hot-100-btn-label">Looking For</span>
                                            <a href="#" class="btn btn-selected-blue">Women</a>
                                            <a href="#" class="btn btn-grey">Men</a>
                                        </div> <!-- .filter-group -->
                                        <div class="filter-group">
                                            <label for="filter-state">Location</label>
                                            <div class="fg-field">
                                                <select id="filter-state">
                                                    <option>California</option>
                                                    <option>New York</option>
                                                </select>
                                            </div> <!-- .fg-field -->
                                        </div> <!-- .filter-group -->
                                    </form>
                                </div>
                            </div> <!-- .hot-100-main-list-top -->
                            <div class="hot-100-newest-gps-wrap">
                                <div class="hot-100-newest-gp active">
                                    <div class="hot-100-newest-gp-in">
                                        <p>Newest <strong>Female Members</strong> between the age of <span class="tag-red">21 to 24</span></p>
                                        <div class="hot-100-newest-slider-wrap">
                                            <a href="#" class="hot-100-newest-gp-nav prev"></a>
                                            <a href="#" class="hot-100-newest-gp-nav next"></a>
                                            <div class="slider-in">
                                                <div class="slider-in-2 clearfix">
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                </div> <!-- .slider-in-2 -->
                                            </div> <!-- .slider-in -->
                                        </div> <!-- .hot-100-newest-slider-wrap -->
                                    </div> <!-- .hot-100-newest-gp-in -->
                                </div> <!-- .hot-100-newest-gp -->
                                <div class="hot-100-newest-gp">
                                    <div class="hot-100-newest-gp-in">
                                        <p>Newest <strong>Female Members</strong> between the age of <span class="tag-red">21 to 24</span></p>
                                        <div class="hot-100-newest-slider-wrap">
                                            <a href="#" class="hot-100-newest-gp-nav prev"></a>
                                            <a href="#" class="hot-100-newest-gp-nav next"></a>
                                            <div class="slider-in">
                                                <div class="slider-in-2 clearfix">
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                </div> <!-- .slider-in-2 -->
                                            </div> <!-- .slider-in -->
                                        </div> <!-- .hot-100-newest-slider-wrap -->
                                    </div> <!-- .hot-100-newest-gp-in -->
                                </div> <!-- .hot-100-newest-gp -->
                                <div class="hot-100-newest-gp">
                                    <div class="hot-100-newest-gp-in">
                                        <p>Newest <strong>Female Members</strong> between the age of <span class="tag-red">21 to 24</span></p>
                                        <div class="hot-100-newest-slider-wrap">
                                            <a href="#" class="hot-100-newest-gp-nav prev"></a>
                                            <a href="#" class="hot-100-newest-gp-nav next"></a>
                                            <div class="slider-in">
                                                <div class="slider-in-2 clearfix">
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                </div> <!-- .slider-in-2 -->
                                            </div> <!-- .slider-in -->
                                        </div> <!-- .hot-100-newest-slider-wrap -->
                                    </div> <!-- .hot-100-newest-gp-in -->
                                </div> <!-- .hot-100-newest-gp -->
                                <div class="hot-100-newest-gp">
                                    <div class="hot-100-newest-gp-in">
                                        <p>Newest <strong>Female Members</strong> between the age of <span class="tag-red">21 to 24</span></p>
                                        <div class="hot-100-newest-slider-wrap">
                                            <a href="#" class="hot-100-newest-gp-nav prev"></a>
                                            <a href="#" class="hot-100-newest-gp-nav next"></a>
                                            <div class="slider-in">
                                                <div class="slider-in-2 clearfix">
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                </div> <!-- .slider-in-2 -->
                                            </div> <!-- .slider-in -->
                                        </div> <!-- .hot-100-newest-slider-wrap -->
                                    </div> <!-- .hot-100-newest-gp-in -->
                                </div> <!-- .hot-100-newest-gp -->
                                <div class="hot-100-newest-gp">
                                    <div class="hot-100-newest-gp-in">
                                        <p>Newest <strong>Female Members</strong> between the age of <span class="tag-red">21 to 24</span></p>
                                        <div class="hot-100-newest-slider-wrap">
                                            <a href="#" class="hot-100-newest-gp-nav prev"></a>
                                            <a href="#" class="hot-100-newest-gp-nav next"></a>
                                            <div class="slider-in">
                                                <div class="slider-in-2 clearfix">
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                    <div class="hot-100-slide">
                                                        <div class="hot-100-slide-pic">
                                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-newest.jpg" alt="" class="block" />
                                                            <span class="hot-100-main-list-ttl"><span>Marissa</span></span>
                                                        </div>
                                                        <div class="hot-100-slide-text">
                                                            21 Years
                                                            <br />City • Login
                                                        </div>
                                                    </div> <!-- .hot-100-slide -->
                                                </div> <!-- .slider-in-2 -->
                                            </div> <!-- .slider-in -->
                                        </div> <!-- .hot-100-newest-slider-wrap -->
                                    </div> <!-- .hot-100-newest-gp-in -->
                                </div> <!-- .hot-100-newest-gp -->
                            </div> <!-- .hot-100-newest-gps-wrap -->
                        </div> <!-- #hot-100-main -->
                    </div> <!-- #more-main-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>
</body>
</html>