<?php $this->getHeader($this->title, 'page-black', 2) ?>
<div class="sp-wrap hot-wrap-1">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="more-main-content">
                        <?= $this->partial('partials/hottop.phtml', array('active' => 2)) ?>
                        <div id="hot-100-main">
                            <div class="hot-100-main-list-top clearfix">
                                <h2 class="ld">Women Photos</h2>
                                <div class="rd">
                                    <form>
                                        <div class="filter-group">
                                            <span class="vam hot-100-btn-label">Looking For</span>
                                            <a href="#" class="btn btn-selected-blue">Women</a>
                                            <a href="#" class="btn btn-grey">Men</a>
                                        </div> <!-- .filter-group -->
                                        <div class="filter-group">
                                            <label for="filter-state">Location</label>
                                            <div class="fg-field">
                                                <select id="filter-state">
                                                    <option>California</option>
                                                    <option>New York</option>
                                                </select>
                                            </div> <!-- .fg-field -->
                                        </div> <!-- .filter-group -->
                                    </form>
                                </div>
                            </div> <!-- .hot-100-main-list-top -->
                            <div class="pagination clearfix">
                                <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                                <div class="ib-list rd">
                                    <a href="#" class="page active">1</a>
                                    <a href="#" class="page">2</a>
                                    <a href="#" class="page">3</a>
                                </div>
                            </div> <!-- .pagination -->
                            <div class="ib-list hot-100-fotos-list">
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-1-1.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-1-2.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-1-3.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-1-4.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-2.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-3.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-4.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-5.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-6.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-7.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-8-1.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-8-2.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-8-3.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-5.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-9-1.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-9-2.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-9-3.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-6.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-7.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-10.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-11.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-12-1.jpg" alt="" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-12-3.jpg" alt="" class="rd" />
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-12-2.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->
                                <a href="<?= $this->lurl('hot100/models/1234') ?>" class="ib-block">
                                    <span class="hot-100-fotos-list-pics">
                                        <span class="clearfix">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-foto-13.jpg" alt="" />
                                        </span>
                                        <span class="hot-100-main-list-ttl"><span>Katherine_7867</span></span>
                                    </span> <!-- .hot-100-fotos-list-pics -->
                                    <span class="hot-100-fotos-list-ttl">
                                        23 Years
                                        <br />San Francisco, CA
                                    </span>
                                </a> <!-- .ib-block -->

                            </div> <!-- .hot-100-fotos-list -->
                            <div class="pagination clearfix">
                                <div class="ld">Showing <strong>1&ndash;8</strong> of <strong>30</strong> Results</div>
                                <div class="ib-list rd">
                                    <a href="#" class="page active">1</a>
                                    <a href="#" class="page">2</a>
                                    <a href="#" class="page">3</a>
                                </div>
                            </div> <!-- .pagination -->
                        </div> <!-- #hot-100-main -->
                    </div> <!-- #more-main-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>
</body>
</html>