<?php $this->getHeader($this->title, 'page-black', 2) ?>
<div class="sp-wrap hot-wrap-1">
    <div class="in">
        <div class="subpage-content">
            <div id="members-content-wrap">
                <div class="clearfix">
                    <div id="more-main-content">
                        <?= $this->partial('partials/hottop.phtml', array('active' => 3)) ?>
                        <div id="hot-100-main">
                            <div class="hot-100-main-list-top clearfix">
                                <h2 class="ld">Women Videos</h2>
                                <div class="rd">
                                    <form>
                                        <div class="filter-group">
                                            <span class="vam hot-100-btn-label">Looking For</span>
                                            <a href="#" class="btn btn-selected-blue">Women</a>
                                            <a href="#" class="btn btn-grey">Men</a>
                                        </div> <!-- .filter-group -->
                                        <div class="filter-group">
                                            <label for="filter-state">Location</label>
                                            <div class="fg-field">
                                                <select id="filter-state">
                                                    <option>California</option>
                                                    <option>New York</option>
                                                </select>
                                            </div> <!-- .fg-field -->
                                        </div> <!-- .filter-group -->
                                    </form>
                                </div>
                            </div> <!-- .hot-100-main-list-top -->
                            <div class="ib-list hot-100-videos-list">
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-1.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-2.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-3.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-4.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-5.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-6.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-1.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-2.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-3.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-4.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-5.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-6.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-1.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-2.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-3.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-4.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                    <div class="hot-100-videos-list-ibb-in">
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-5.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                                <div class="ib-block">
                                    <div class="hot-100-videos-list-ibb-in">
                                        <span class="hot-100-videos-list-custom-label">Custom Label</span>
                                        <a href="<?= $this->lurl('videos/1234') ?>" class="link-video">
                                            <img src="<?= $this->baseUrl() ?>/images/clipart/hot-100-video-6.jpg" alt="" />
                                            <span class="play-icon-small"></span>
                                        </a>
                                        <div class="hot-100-videos-list-ttl">
                                            <strong>Katherine_7867</strong>
                                            <br />San Francisco, CA
                                        </div>
                                    </div> <!-- .hot-100-videos-list-ibb-in -->
                                </div> <!-- .ib-block -->
                            </div> <!-- .hot-100-fotos-list -->
                        </div> <!-- #hot-100-main -->
                    </div> <!-- #more-main-content -->
                    <?php $this->getSidebar(array('search', 'account', 'favorites')) ?>
                </div> <!-- .clearfix -->
            </div> <!-- #members-content -->
        </div> <!-- .subpage-content -->
    </div> <!-- .in -->
</div> <!-- .sp-wrap -->
<?php $this->getFooter() ?>
</body>
</html>