<?php $this->getHeader($this->title, 'page-white', 0) ?>
<div class="dashboard-sub-wrap">
    <div class="in">
        <div id="members-content-wrap">
            <div id="dashboard-top">
                <div class="clearfix">
                    <h1 class="ttl-sub-1 ld">my dashboard</h1>
                    <div class="rd">
                        <?= $this->partial('partials/dashmenu.phtml', array('active' => 4)) ?>
                    </div> <!-- .rd -->
                </div> <!-- .clearfix -->
            </div> <!-- #dashboard-top -->
            <div class="clearfix">
                <div id="dashboard-content">
                    <form>
                        <div class="dashboard-settings-block">
                            <div class="db-set-form-col">
                                <h2>Change your Password</h2>
                                <div class="form-row">
                                    <label for="f1">Current Password</label>
                                    <div class="form-field"><input type="password" class="text" id="f1" /></div>
                                </div> <!-- .form-row -->
                                <div class="form-row">
                                    <label for="f2">New Password</label>
                                    <div class="form-field"><input type="password" class="text" id="f2" /></div>
                                </div> <!-- .form-row -->
                                <div class="form-row">
                                    <label for="f3">Confirm New Password</label>
                                    <div class="form-field"><input type="password" class="text" id="f3" /></div>
                                </div> <!-- .form-row -->
                            </div> <!-- .db-set-form-col -->
                        </div> <!-- .dashboard-settings-block -->
                        <div class="dashboard-settings-block">
                            <div class="ra"><a href="#" class="btn btn-blue db-set-submit-1">Update Password</a></div>
                        </div> <!-- .dashboard-settings-block -->
                    </form>
                </div> <!-- #dashboard-content -->

                <div id="members-sidebar" class="dashboard-sidebar">
                    <?= $this->partial('partials/dashsettings.phtml', array('active' => 2)) ?>
                    <?= $this->partial('partials/dashsidebar.phtml') ?>
                </div> <!-- #members-sidebar.dashboard-sidebar -->
            </div>
        </div> <!-- #members-content-wrap -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>