<?php $this->getHeader($this->title, 'page-white', 0) ?>
<div class="dashboard-sub-wrap">
    <div class="in">
        <div id="members-content-wrap">
            <div id="dashboard-top">
                <div class="clearfix">
                    <h1 class="ttl-sub-1 ld">my dashboard</h1>
                    <div class="rd">
                        <?= $this->partial('partials/dashmenu.phtml', array('active' => 4)) ?>
                    </div> <!-- .rd -->
                </div> <!-- .clearfix -->
            </div> <!-- #dashboard-top -->
            <div class="clearfix">
                <div id="dashboard-content">
                    <form>
                        <div class="dashboard-settings-block">
                            <h2>Privacy Settings</h2>
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f1" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f1">Locked Profiles</label></div>
                                <div class="ib-block db-set-privacy-3">2 <span class="db-set-sep">&nbsp;&bull;&nbsp;</span>  <a href="#">View blocked profiles</a></div>
                            </div> <!-- .form-row -->
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f2" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f2">Private Profile</label></div>
                                <div class="ib-block db-set-privacy-3">Prevent my profile from showing up in search results</div>
                            </div> <!-- .form-row -->
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f3" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f3">Show Gifts Sent/Received</label></div>
                                <div class="ib-block db-set-privacy-3">Show the gifts I've sent/received to other users.</div>
                            </div> <!-- .form-row -->
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f4" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f4">Private Access</label></div>
                                <div class="ib-block db-set-privacy-3">Manage private photo access</div>
                            </div> <!-- .form-row -->
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f5" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f5">Enable Facebook &lsquo;Like&rsquo;</label></div>
                                <div class="ib-block db-set-privacy-3">Show a Facebook 'Like' button on my profile</div>
                            </div> <!-- .form-row -->
                            <div class="form-row ib-list">
                                <div class="ib-block db-set-privacy-1"><input type="checkbox" id="f6" /></div>
                                <div class="ib-block db-set-privacy-2"><label for="f6">Data sharing</label></div>
                                <div class="ib-block db-set-privacy-3">Do not share data with third parties</div>
                            </div> <!-- .form-row -->
                        </div> <!-- .dashboard-settings-block -->
                        <div class="dashboard-settings-block">
                            <div class="ra"><a href="#" class="btn btn-blue db-set-submit-1">Save Changes</a></div>
                        </div> <!-- .dashboard-settings-block -->
                    </form>
                </div> <!-- #dashboard-content -->

                <div id="members-sidebar" class="dashboard-sidebar">
                    <?= $this->partial('partials/dashsettings.phtml', array('active' => 3)) ?>
                    <?= $this->partial('partials/dashsidebar.phtml') ?>
                </div> <!-- #members-sidebar.dashboard-sidebar -->
            </div>
        </div> <!-- #members-content-wrap -->
    </div> <!-- .white-box-1 -->
</div> <!-- .sub-wrap -->
<?php $this->getFooter() ?>